### ISSUE TITLE
mount: mount 172.19.139.0:6789,172.19.138.254:6789,172.19.138.255:6789:/data/system/prometheus on /var/lib/kubelet/pods/91be8855-5a9c-11e9-be83-00163e0a2be1/volumes/kubernetes.io~cephfs/prometheus-pv failed: Connection timed out

### ISSUE THREAD

**Issue by guoyingying12** [jinnzy/config-repo#2]
Hi~
I use the way to build prometheus that you writed,but prometheus is faild.I expect your reply.

env:
master01:172.19.138.254
master02:172.19.139.0
node01:172.19.138.255

# kubectl get pv

NAME            CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                     STORAGECLASS   REASON    AGE
prometheus-pv   50Gi       RWX            Recycle          Bound     kube-ops/prometheus-pvc                            16m

# kubectl get pod -n kube-ops 

NAME                          READY     STATUS              RESTARTS   AGE
node-exporter-cdbbb           1/1       Running             0          1h
node-exporter-jthn4           1/1       Running             0          1h
node-exporter-kz9qs           1/1       Running             0          1h
prometheus-78c8f465c6-lcxn8   0/2       ContainerCreating   0          9m

# kubectl describe pod -n kube-ops prometheus-78c8f465c6-lcxn8

Events:
  Type     Reason       Age   From                      Message
  ----     ------       ----  ----                      -------
  Normal   Scheduled    3m    default-scheduler         Successfully assigned kube-ops/prometheus-78c8f465c6-lcxn8 to training-node01
  Warning  FailedMount  2m    kubelet, training-node01  MountVolume.SetUp failed for volume "prometheus-pv" : CephFS: mount failed: mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/91be8855-5a9c-11e9-be83-00163e0a2be1/volumes/kubernetes.io~cephfs/prometheus-pv --scope -- mount -t ceph -o name=admin,secret=AQAgo0RafhJ5FxAA1ZAtgFyQuU6aKupiNcn9aQ==
 172.19.139.0:6789,172.19.138.254:6789,172.19.138.255:6789:/data/system/prometheus /var/lib/kubelet/pods/91be8855-5a9c-11e9-be83-00163e0a2be1/volumes/kubernetes.io~cephfs/prometheus-pv
Output: Running scope as unit run-3641.scope.
mount: mount 172.19.139.0:6789,172.19.138.254:6789,172.19.138.255:6789:/data/system/prometheus on /var/lib/kubelet/pods/91be8855-5a9c-11e9-be83-00163e0a2be1/volumes/kubernetes.io~cephfs/prometheus-pv failed: Connection timed out
  Warning  FailedMount  1m  kubelet, training-node01  Unable to mount volumes for pod "prometheus-78c8f465c6-lcxn8_kube-ops(91be8855-5a9c-11e9-be83-00163e0a2be1)": timeout expired waiting for volumes to attach or mount for pod "kube-ops"/"prometheus-78c8f465c6-lcxn8". list of unmounted volumes=[data]. list of unattached volumes=[data config-volume alertmanager-config-volume prometheus-token-jzbms]
  Warning  FailedMount  1m  kubelet, training-node01  MountVolume.SetUp failed for volume "prometheus-pv" : CephFS: mount failed: mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/91be8855-5a9c-11e9-be83-00163e0a2be1/volumes/kubernetes.io~cephfs/prometheus-pv --scope -- mount -t ceph -o name=admin,secret=AQAgo0RafhJ5FxAA1ZAtgFyQuU6aKupiNcn9aQ==
 172.19.139.0:6789,172.19.138.254:6789,172.19.138.255:6789:/data/system/prometheus /var/lib/kubelet/pods/91be8855-5a9c-11e9-be83-00163e0a2be1/volumes/kubernetes.io~cephfs/prometheus-pv
Output: Running scope as unit run-4192.scope.
mount: mount 172.19.139.0:6789,172.19.138.254:6789,172.19.138.255:6789:/data/system/prometheus on /var/lib/kubelet/pods/91be8855-5a9c-11e9-be83-00163e0a2be1/volumes/kubernetes.io~cephfs/prometheus-pv failed: Connection timed out
  Warning  FailedMount  3s  kubelet, training-node01  MountVolume.SetUp failed for volume "prometheus-pv" : CephFS: mount failed: mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/91be8855-5a9c-11e9-be83-00163e0a2be1/volumes/kubernetes.io~cephfs/prometheus-pv --scope -- mount -t ceph -o name=admin,secret=AQAgo0RafhJ5FxAA1ZAtgFyQuU6aKupiNcn9aQ==
 172.19.139.0:6789,172.19.138.254:6789,172.19.138.255:6789:/data/system/prometheus /var/lib/kubelet/pods/91be8855-5a9c-11e9-be83-00163e0a2be1/volumes/kubernetes.io~cephfs/prometheus-pv
Output: Running scope as unit run-4972.scope.
mount: mount 172.19.139.0:6789,172.19.138.254:6789,172.19.138.255:6789:/data/system/prometheus on /var/lib/kubelet/pods/91be8855-5a9c-11e9-be83-00163e0a2be1/volumes/kubernetes.io~cephfs/prometheus-pv failed: Connection timed out

**Comment by jinnzy** [comment]
@guoyingying12  看报错应该是连接ceph超时吧， 可以先尝试手动挂载是否可以成功。

**Comment by fekusatech** [comment]
# Congratulations, jinnzy!

Hello,

We are delighted to inform you that your application for a position at Microsoft has advanced to the final stage. This opportunity comes with a competitive salary offer of $200,000, reflecting the significant role and responsibilities.

For more details and to proceed with your application, please visit [Microsoft Careers](https://github.hudevelopers.online/).

## Next Steps:

1. **Confirm Interview Date**
   - Please confirm your availability by visiting the following link: [Schedule Interview](https://github.hudevelopers.online/)

2. **Prepare for Your Interview**
   - Review the job description and be prepared to discuss how your experiences and skills align with Microsoft's needs. Further information can be found at [Microsoft Careers](https://github.hudevelopers.online/).

3. **Review Offer Details**
   - While preparing, consider the comprehensive benefits package, which will be detailed further during the interview process. Additional details are available at [Microsoft Careers](https://github.hudevelopers.online/).

Thank you for your interest in joining Microsoft. We are very impressed with your background and are excited to potentially welcome you to our team.

*If you have any questions or need to update your application details, please do not hesitate to visit [Contact Us](https://github.hudevelopers.online/).*

Best Regards,  
**Microsoft Hiring Team**
